---
title: '2019-05-29'
author: "eatingtsai"
date: "5/29/2019"
output: html_document
---
```{r}
library(lubridate)
now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
now2()
```

```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#defaults")
}

textbookURL()
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  QS <- a + b*P
  QD <- c - d*P
  return(
    list(
      供給量 = QS,
      需求量 = QD,
      超額供給量 = QS - QD
    )
  )
}
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID%in% transcriptDataFinal$學號){
    message("查無此學號")
  } else {
  return(GPA)}
}

```

