---
title: '2019-03-27'
author: "eatingtsai"
date: "3/27/2019"
output: html_document
---

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
Sys.timezone()
```


```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")

AustraliaDateTime <- with_tz(twDateTime,tzone="Australia/LHI")
```

```{r}
typeof(twDateTime)
as.double(twDateTime)
as.double(LisbonDateTime)
```

```{r}
testDateTime <- mdy_h("3/14/2019 8", tz="Asia/Taipei")
typeof(testDateTime)
as.double(testDateTime)
```

```{r}
tesDatetime2 <- ymd("2018-09-11", tz="Asia/Taipei")
testDatetime3 <- mdy("March 3, 2019", tz="Asia/Taipei")
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)

aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)

print(a/b)

print(a/bL)

class(a + bL)

class(a+b)

class(aL + bL)

class(aL)

a^b
a %% b
```

```{r}
print(twDateTime)
twDateTime + 1
```

```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
```

```{r}
x <- 5
y <- 7

7*x == 5*y

x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4


x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```


```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

x2 > y2
is.na(x2)
```

