---
title: '2019-05-15'
author: "eatingtsai"
date: "5/15/2019"
output: html_document
---
```{r}
Vector1 <- letters[1:6]
Vector1
```
```{r}

names(Vector1)
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```


```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1

colnames(matObj1) 
rownames(matObj1)
colnames(matObj1) <-c('欄位1','欄位2','欄位3')
colnames(matObj1)
matObj1

rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b$元素3 <- "False"
b[[5]] <- "7"
b
```

```{r}
newmember <- c(2, 5, 1)
as.integer(newmember)
b$元素2 <- "Hi"
b$新成員 <- newmember
b
```


```{r}
library(readr)
library(lubridate)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
```{r}
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis <- exData3$期間 >= ymd("1997-06-01") & exData3$期間 <= ymd("1998-12-01")
exData3
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")

transcriptDataFinal$學號=="92aS67fee" -> a
transcriptDataFinal[a,]
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
class(utility_cobb_douglass)
```

```{r}
test <- function(.alpha,.beta){
  output <- .alpha + .beta
  return(output)
}
```

```{r}
supply_fun <- function(a, b, P){
  Qs <- a + b * P
  return(Qs)
}
```

```{r}
demand_fun <- function(c, d, P){
  Qd <- c - d * P
  return(Qd)
}
```

```{r}
supply_fun(P-1, 0, 1)
demand_fun(P-1, 5, 1)
```

