---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
b<-"你好"
```
#'' " "差別
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
# 加總向量內的所有元素值。
sum(aLogical)
```

#factor
```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)

class(studentMajors)

levels(studentMajors)

as.integer(studentMajors)
```

```{r}
studentMajors1 <- c("經濟系", "經濟系", "法律系")

class(studentMajors1)
```


```{r}
birthplace <- factor(
  c("台北市","台北市","台中市","台北市","台中市")
)

class(birthplace)

levels(birthplace)

typeof(birthplace)

as.integer(birthplace)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
sum(stringInteger)

trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
sum(trueInteger)
```
```{r}
trueInteger <- as.character(stringInteger)
class(trueInteger)
# 無法進行數值運算
sum(trueInteger)
```

```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)

class(dtObject)

dtObject 

typeof(dtObject)

as.double(dtObject)
```

